# Generated by Django 3.1.1 on 2020-09-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('added_date', models.DateField()),
                ('time', models.PositiveIntegerField()),
                ('importance', models.CharField(choices=[('最重要', '最重要'), ('重要', '重要'), ('急ぎでない', '急ぎでない')], max_length=10, verbose_name='重要度')),
            ],
        ),
    ]
